# Generated by Django 3.1.13 on 2021-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0004_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
